[package]
name = "archwiki-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
fuzzy-matcher = "0.3.7"
itertools = "0.10.5"
reqwest = "0.11.17"
scraper = "0.16.0"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
