[package]
name = "archwiki-rs"
description = "A CLI tool to read pages from the ArchWiki"
version = "2.2.1"
edition = "2021"
authors = ["Lucy Gschwantner lucygschwantner@gmail.com"]
homepage = "https://github.com/Jackboxx/archwiki-rs"
license = "MIT"
repository = "https://github.com/jackboxx/archwiki-rs"
readme = "README.md"
keywords = ["ArchWiki", "cli"]
categories = ["command-line-interface"]

[dependencies]
assert_fs = "1.0.13"
clap = { version = "4.4.7", features = ["derive"] }
colored = "2.0.0"
directories = "5.0.1"
ego-tree = "0.6.2"
futures = "0.3.28"
html2md = "0.2.14"
human-panic = "1.1.5"
indicatif = "0.17.6"
itertools = "0.10.5"
num_cpus = "1.16.0"
regex = "1.9.3"
reqwest = "0.11.17"
scraper = "0.16.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serde_yaml = "0.9.21"
termination = "0.1.2"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
url = "2.4.1"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.3"
pretty_assertions = "1.4.0"
