[package]
name = "archwiki-rs"
description = "A CLI tool to read pages from the ArchWiki"
version = "1.1.0"
edition = "2021"
authors = ["Lucy Gschwantner lucygschwantner@gmail.com"]
license = "MIT"
repository = "https://github.com/jackboxx/archwiki-rs"
readme = "README.md"
keywords = ["ArchWiki", "cli", "bar"]
categories = ["command-line-interface"]

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
colored = "2.0.0"
directories = "5.0.1"
ego-tree = "0.6.2"
fuzzy-matcher = "0.3.7"
html2md = "0.2.14"
itertools = "0.10.5"
reqwest = "0.11.17"
scraper = "0.16.0"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
