name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get tag
        id: get_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - if: startsWith(github.event.head_commit.message, 'Bump the cli-dependencies group')
        name: github release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: gh release create ${{ steps.get_tag.outputs.tag }} --generate-notes

      - if: startsWith(github.event.head_commit.message, 'Bump the cli-dependencies group')
        name: crates.io release
        shell: bash
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
