name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: github release
        uses: softprops/action-gh-release@v1

      - name: crates.io release
        shell: bash
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
