name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: github release
        uses: softprops/action-gh-release@v1

      - name: crates.io release
        shell: bash
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
