name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: get latest tag
        id: get_latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - if: startsWith(github.event.head_commit.message, 'Bump the cli-dependencies group')
        name: github release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.event.head_commit.message, 'Bump the cli-dependencies group')
        name: crates.io release
        shell: bash
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
